# This is a basic workflow to help you get started with Actions

name: CI build-Android

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ test-Action ]
    tags:
      - 'v*'
  pull_request:
    branches: [ test-Action ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
#     runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Installing Tree
      run: sudo apt-get install tree
    - name: Showing Tree
      run: |
        tree ../ -L 1
        tree ../../ -L 2
        tree ../../ -L 3 -d
        tree -L 4
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm ci
    - name: Install @angular/cli
      run: |
        npm i -D -E @angular/cli  
        npm install -g @ionic/cli
        
    - name: Build Android APK'
      run: |
        ionic build
        npx cap sync
        cd android/
        ./gradlew assembleDebug
        cd ..
    - name: Build Android Release
      run: |
        cd android && ./gradlew assembleRelease    
        
    - name: Showing Tree
      run: tree -L 4
#     - name: Install private-coupon
#       run: npm ci @numbersprotocol/private-coupon@0.0.7
#       env:
#         NODE_AUTH_TOKEN: ${{secrets.MY_PAT_ACTION_TEST}}   

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Run a echo
      run: echo Add test actions ,

 #     這邊 build 完應該進行 測試，然後壓Tag 才觸發 ios-deploy.yml  android-deploy.yml 
       
        

#     - name: Check if version has been updated
#       id: version_check
#       uses: EndBug/version-check@v1
#       with:
#         diff-search: true
#         token: ${{ secrets.GITHUB_TOKEN }}

#     - name: Create GitHub release
#       id: create_release
#       if: steps.version_check.outputs.changed == 'true'
#       uses: actions/create-release@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         tag_name: ${{ steps.version_check.outputs.version }}
#         release_name: ${{ steps.version_check.outputs.version }}
#         body: |
#           ![release!](https://i.giphy.com/media/lPulaaB9lDMnGZiivs/source.gif)
          
#           # Changelog
#           Release type: ${{ steps.version_check.outputs.type }}
#         prerelease: true

#     - name: Upload APKs to release assets
#       if: steps.version_check.outputs.changed == 'true'
#       uses: actions/upload-release-asset@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upload_url: ${{ steps.create_release.outputs.upload_url }}
#         asset_path: ./android/app/build/outputs/apk/debug/app-debug.apk
#         asset_name: app-debug.apk
#         asset_content_type: application/vnd.android.package-archive
